OUT_DIR=../../build/woff2
LIBCOMMON=$(OUT_DIR)/libwoff2common.bc
DEC=$(OUT_DIR)/decompress_binding.js
ENC=$(OUT_DIR)/compress_binding.js

SRC_LIBCOMMON=src/table_tags.cc src/variable_length.cc src/woff2_common.cc
SRC_DEC=../decompress_binding.cc src/woff2_dec.cc src/woff2_out.cc
SRC_ENC=../compress_binding.cc src/font.cc src/glyph.cc src/normalize.cc src/transform.cc src/woff2_enc.cc
MODULE_SETTINGS=../module_settings.js
INCLUDE=include
HDR_IN_SRC=src/

BROTLI_OUT_DIR=../../build/brotli
LIBBROTLICOMMON=$(BROTLI_OUT_DIR)/libbrotlicommon-static.bc
LIBBROTLIDEC=$(BROTLI_OUT_DIR)/libbrotlidec-static.bc
LIBBROTLIENC=$(BROTLI_OUT_DIR)/libbrotlienc-static.bc
BROTLI_INCLUDE=../brotli/c/include

CFLAGS=-std=gnu++11 -s 'ALLOW_MEMORY_GROWTH=1' -s 'EXTRA_EXPORTED_RUNTIME_METHODS=["cwrap"]' -O2
EXPORT_ENC=-s 'EXPORTED_FUNCTIONS=["_main", "_malloc", "_free", "_compress", "_compressed_size"]'
EXPORT_DEC=-s 'EXPORTED_FUNCTIONS=["_main", "_malloc", "_free", "_decompress", "_decompressed_size"]'

.PHONY: all clean

all: $(DEC) $(ENC)

$(LIBCOMMON): $(OUT_DIR)
	emcc $(CFLAGS) -o $(LIBCOMMON) $(SRC_LIBCOMMON)

$(DEC): $(OUT_DIR) $(LIBCOMMON)
	emcc $(CFLAGS) $(EXPORT_DEC) -s WASM=1 -o $(DEC) --pre-js $(MODULE_SETTINGS) -I$(BROTLI_INCLUDE) -I$(INCLUDE) -I$(HDR_IN_SRC) $(SRC_DEC) $(LIBCOMMON) $(LIBBROTLIDEC) $(LIBBROTLICOMMON)

$(ENC): $(OUT_DIR) $(LIBCOMMON)
	emcc $(CFLAGS) $(EXPORT_ENC) -s WASM=1 -o $(ENC) --pre-js $(MODULE_SETTINGS) -I$(BROTLI_INCLUDE) -I$(INCLUDE) -I$(HDR_IN_SRC) $(SRC_ENC) $(LIBCOMMON) $(LIBBROTLIENC) $(LIBBROTLICOMMON)

$(OUT_DIR):
	mkdir $(OUT_DIR)

clean:
	rm -rf OUT_DIR
